In [1]:
import h5py
import numpy as np

file_path = "/code/zhang/SSL4MIS/data/BraTS2019/data/BraTS19_2013_0_1.h5"  # Replace with the actual path to your h5 file

try:
    with h5py.File(file_path, "r") as h5_file:
        # Print the keys of the datasets in the file
        print("Keys in the HDF5 file:")
        print(list(h5_file.keys()))
        
        # Print the content of each dataset
        print("\nContents of the datasets:")
        for key, dataset in h5_file.items():
            print(f"Dataset: {key}")
            print(dataset[:])  # Print the entire dataset's content
            print("\n")
except Exception as e:
    print(f"Error occurred while reading the HDF5 file: {str(e)}")


Keys in the HDF5 file:
['image', 'label']

Contents of the datasets:
Dataset: image
[[[-3.0839508 -3.0839508 -3.0839508 ... -3.0839508 -3.0839508 -3.0839508]
  [-3.0839508 -3.0839508 -3.0839508 ... -3.0839508 -3.0839508 -3.0839508]
  [-3.0839508 -3.0839508 -3.0839508 ... -3.0839508 -3.0839508 -3.0839508]
  ...
  [-3.0839508 -3.0839508 -3.0839508 ... -3.0839508 -3.0839508 -3.0839508]
  [-3.0839508 -3.0839508 -3.0839508 ... -3.0839508 -3.0839508 -3.0839508]
  [-3.0839508 -3.0839508 -3.0839508 ... -3.0839508 -3.0839508 -3.0839508]]

 [[-3.0839508 -3.0839508 -3.0839508 ... -3.0839508 -3.0839508 -3.0839508]
  [-3.0839508 -3.0839508 -3.0839508 ... -3.0839508 -3.0839508 -3.0839508]
  [-3.0839508 -3.0839508 -3.0839508 ... -3.0839508 -3.0839508 -3.0839508]
  ...
  [-3.0839508 -3.0839508 -3.0839508 ... -3.0839508 -3.0839508 -3.0839508]
  [-3.0839508 -3.0839508 -3.0839508 ... -3.0839508 -3.0839508 -3.0839508]
  [-3.0839508 -3.0839508 -3.0839508 ... -3.0839508 -3.0839508 -3.0839508]]

 [[-3.083950

In [7]:
import h5py
import numpy as np

file_path = "/code/zhang/SSL4MIS/data/new.h5"  # Replace with the actual path to your h5 file

try:
    with h5py.File(file_path, "r") as h5_file:
        # Print the keys of the datasets in the file
        print("Keys in the HDF5 file:")
        print(list(h5_file.keys()))
        
        # Print the content of each dataset
        print("\nContents of the datasets:")
        for key, dataset in h5_file.items():
            print(f"Dataset: {key}")
            print(dataset[:])  # Print the entire dataset's content
            print("\n")
except Exception as e:
    print(f"Error occurred while reading the HDF5 file: {str(e)}")


Keys in the HDF5 file:
['images']

Contents of the datasets:
Dataset: images
[[[5 6]
  [3 1]]

 [[8 3]
  [1 7]]]




In [6]:

# Generating a random 3D NumPy array with nested lists
shape = (2, 2, 2)  # Specify the shape of the 3D array (replace with your desired shape)
random_array = np.random.randint(0, 10, size=shape)

# Creating the HDF5 file and saving the array
file_path = "/code/zhang/SSL4MIS/data/new.h5"  # Replace with the desired path for the new h5 file
dataset_name = 'images'  # The key in the HDF5 file where you want to save the data

try:
    with h5py.File(file_path, "w") as h5_file:
        h5_file.create_dataset(dataset_name, data=random_array)
    print(f"Random 3D array saved to {file_path} under the key '{dataset_name}'.")
except Exception as e:
    print(f"Error occurred while saving the random array to the HDF5 file: {str(e)}")


Random 3D array saved to /code/zhang/SSL4MIS/data/new.h5 under the key 'images'.
